// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs
// Paste this text to https://dbdiagram.io to view the database

enum roles {
  user
  maintainer
  admin
}

table users {
  id integer [primary key]
  username integer
  email varchar
  password varchar [note: 'encrypted!']
  role roles
}

Table game_titles {
  id integer [primary key]
  name varchar [note: 'SOUND VOLTEX, Wangan Midnight Maximum Tune, etc']
}

Table game_title_versions {
  id integer [primary key]
  title_id integer [note: "Shown in JSON response as a title object"]
  name varchar [note: 'the "EXCEED GEAR" part of "SOUND VOLTEX EXCEED GEAR"']
  price_info text [note: 'Some arcade games have different systems for determining "one play", e.g. SDVX requires at least 5 card swipes to play a game of 3 songs. The info is given here']
}

Ref: game_title_versions.title_id > game_titles.id

Table cities {
  id integer [primary key]
  name varchar
}

Table arcade_centers {
  id integer [primary key]
  name varchar [note: "Timezone, Game Master, etc"]
  info text [note: 'Notably, Timezone has its own TIZO currency. Other than that, probably just tell the various promo a customer can get']
}

Table arcade_locations {
  id integer [primary key]
  game_center_id integer [note: "Shown in JSON response as a game_center object"]
  city_id integer [note: "Shown in JSON response as a city object"]
  name varchar [note: '"Bandung Indah Mall", "23Paskal", etc. the display name on the listing is shown as arcade_centers.name + arcade_locations.name']
  lat float
  long float
  description text
}

Ref: arcade_locations.game_center_id > arcade_centers.id
Ref: arcade_locations.city_id > cities.id

Table arcade_machines {
  id integer [primary key]
  title_version_id integer [note: "Shown in JSON response as a title_version object"]
  arcade_location_id integer [note: "Shown in JSON response as a arcade_location object"]
  machine_count int [note: 'how many machines/cabinets are in the place']
  price int
  notes text
}

Ref: arcade_machines.title_version_id > game_title_versions.id
Ref: arcade_machines.arcade_location_id > arcade_locations.id
